server:
  port: 10010
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # 路由id，可以任意
        - id: user-service-route
          # 代理的服务地址
          uri: lb://user-service #lb表示从eureka中获取具体服务 http://localhost:10010/user/8 --> http://127.0.0.1:9091/user/8
          # 路由断言： 可以匹配映射路径
          predicates:
            - Path=/**
          filters:
            # 添加请求路径的前缀,成功则正常访问：http://localhost:10010/8
            - PrefixPath=/user

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true