server:
  port: 10010
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # 路由id，可以任意
        - id: user-service-route
          # 代理的服务地址
          uri: lb://user-service #lb表示从eureka中获取具体服务 http://localhost:10010/user/8 --> http://127.0.0.1:9091/user/8
          # 路由断言： 可以匹配映射路径
          predicates:
            - Path=/user/**
          filters:
            # 自定义过滤器，访问 http://localhost:10010/user/8?name=itcast
            - MyParam=name
      default-filters:
        # 响应头过滤器，对输出的响应设置其头部属性名称为X-Response-Default-MyName，值为itcast；如果有多个参数多则重写一行设置不同的参数
        # http://localhost:10010/user/8
        - AddResponseHeader=X-Response-Default-MyName, itcast

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true